local Tunnel = module("vrp", "lib/Tunnel")
_p = Tunnel.getInterface("passos_discord")

Citizen.CreateThread(function()
	local user_id = _p.returnID()
	SetDiscordAppId(817651000751685663)
	SetDiscordRichPresenceAsset('logo') 
	SetDiscordRichPresenceAssetText('Jughead Jones - Passos#2514') 
	SetDiscordRichPresenceAssetSmall('small')
	SetDiscordRichPresenceAssetSmallText('FiveM')
	SetRichPresence('Jughead Jones está programando - ID: '.. user_id) 
	SetDiscordRichPresenceAction(0, 'Button 1', 'URL')
	SetDiscordRichPresenceAction(1,'Buttton 2', 'URL')
end)